### ISSUE TITLE
Delete custom properties issue

### ISSUE THREAD

**Issue by zengbo0710** [ff4j/ff4j#452] opened 2020-09-28 01:33 UTC
Create custom property on UI (version 1.8.7)
name: user/delete/{id}
value: DELETE

Property: user/delete/{id}=DELETE

I got the following error when I delete the above custom property from the UI.
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986

**Comment by clun** [comment] 2020-10-03 12:46
Hello,

I cannot reproduce the error, can you please give me your data set.

<img width="598" alt="Screenshot 2020-10-03 at 14 45 39" src="https://user-images.githubusercontent.com/726536/94992005-1ec6c900-0587-11eb-8091-ca6656e3ed9c.png">

<img width="1237" alt="Screenshot 2020-10-03 at 14 44 21" src="https://user-images.githubusercontent.com/726536/94991988-035bbe00-0587-11eb-98a2-0be5f404f794.png">

**Comment by clun** [comment] 2020-10-03 12:58
If you are using Chinese characters I have not action at ff4j level to help you. You would have to setup a different application server of fix some encodings, we are using UTF-8  where ever we can.
https://stackoverflow.com/questions/48655291/java-lang-illegalargumentexception-invalid-character-found-in-the-request-targe#48682084

**Comment by zengbo0710** [comment] 2020-10-03 14:00
![image](https://user-images.githubusercontent.com/2897576/94993452-ac280e80-05c3-11eb-86c6-db416c08dfde.png)

Custom properties can't be deleted.

**Comment by clun** [comment] 2022-12-19 21:55
I would close this for now the custom properties can be delete by clickng the bin icon.

<img width="600" alt="Screenshot 2022-12-19 at 22 54 21" src="https://user-images.githubusercontent.com/726536/208531553-d29f8aea-08aa-42ca-9e93-9fd4ab7e9839.png">

**Closed by clun** 2022-12-19 21:55 UTC
Labels: PENDING
