### ISSUE TITLE
FF4J support for multiple tenants for SAAS solutions 

### ISSUE THREAD

**Issue by ckurdekar** [ff4j/ff4j#434] opened 2020-07-21 14:00 UTC
@clun 

Looking for functionality to enhance FF4J for multiple tenancy to config same features for various tenancy. Each tenant will have separate ACL, strategies etc ..feature definations can remain same accross all tenant. Having multi tenancy, every tenant data should be segregated and cross tenant should not view/modify others tenant data.
In SAAS base cloud deployment, same solutions i.e Software as service will be sold to various tenants and SAAS administrator wants to control features for various tenants. 

Note Tenant is the Enterprise customer who is purchasing services for there organization. Some feature may or may not be enabled for all tenant.

**Comment by clun** [comment] 2020-07-27 11:57
Agree.

V2 would have Configurations with a name you can associate to some scope : 
```
tenant => Applications => Environment
```

**Comment by kr1929uti** [comment] 2022-12-05 09:59
how to implement feature flags for multi tenants ?

**Comment by clun** [comment] 2022-12-07 13:49
[V2](https://github.com/ff4j/ff4j-v2) offers the proper data model but had never been implemented as no backer nor support.

**Comment by clun** [comment] 2022-12-19 21:52
This required a total rework of the data model. I will close the issue from here, it is available by design in V2 when available.

**Closed by clun** 2022-12-19 21:52 UTC
Labels: V2

**Comment by mcampster** [comment] 2023-05-17 06:18
I see v2 has been released; has this been implemented? If so,  any documentation as to how we can use it? Thanks
