### ISSUE TITLE
Error in Web-Console after adding new feature

### ISSUE THREAD

**Issue by rd-florian-pause** [ff4j/ff4j#585] opened 2022-08-22 07:12 UTC
After adding a new feature when the web console tries to load all the features (and display them in a table) i get the following error message: "Cannot invoke `org.ff4j.core.Feature.getFlippingStrategy()" because "feature" is null` and no data is loaded into the table.

fyi:
I downgraded the thymeleaf version to 3.0.14.RELEASE according to [this issue](https://github.com/ff4j/ff4j/issues/548).

FF4J: 1.8.13
Java: 17

Thanks in advance!

**Comment by clun** [comment] 2022-12-18 14:01
I mark it as duplicate of #548 and working on it and testing.

**Closed by clun** 2022-12-18 14:01 UTC
