### ISSUE TITLE
How do I specify the dynamoDB table name?

### ISSUE THREAD

**Issue by tonyqian66** [ff4j/ff4j#543] opened 2022-01-19 19:23 UTC
I use DynamoDB and ff4j. I create DynamoDB table through AWS management console. How do I let ff4j or FeatureStoreDynamoDB know the table to use. BTW, there is no any message even ff4j can not connect to table for ff4j.

**Comment by clun** [comment] 2022-12-16 09:31
Duplicate of #611 I would close this one to this the other. Adding a constructor to provide table name

**Closed by clun** 2022-12-16 09:31 UTC
Labels: question
